
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: Nat@1408
  port: 6001
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: peekads_development

test:
  <<: *default
  database: peekads_test

production:
  <<: *default
  database: peekads_production
  username: peekads
  password: <%= ENV["PEEKADS_DATABASE_PASSWORD"] %>
